---
dependencies:
  - { role: b-common }
  - { role: b-database-common }  # Role with things required for DB server and/or client. This role needs the server stuff.
  - role: b-spiped-server
    spiped_service_port: 5432
    spiped_port: "{{postgres_spiped_port}}"
    spiped_servicename: postgres
