---
- name: Create directory for environment files
  file:
    path: "{{ frontend_environ_dir }}"
    state: directory
    owner: root
    mode: 700
- name: Install docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{frontend_environ_dir}}/docker-compose.yml"
    owner: root

- name: Enable the {{frontend_container_name}} Docker service
  docker_compose:
    project_src: "{{frontend_environ_dir}}"
    state: present
