---
parserOptions:
    ecmaVersion: 8
    sourceType: module
    ecmaFeatures:
        impliedStrict: true
env:
    browser: false
    node: true
    es6: true
    mocha: true
extends:
    - eslint:recommended
rules:
    strict: 0
    indent: 2
    no-unused-vars: ["error", { "argsIgnorePattern": "^(event$|_)", }]
