/**
 * Miscellaneous helper methods for the Ratio express.js server
 */

/**
 * When using a budget's open_count (the "safe ID prefix") to generate new IDs,
 * multiply the open_count by this number, then increment until the ID is unused.
 * 
 * In other words, if the open_count is 4, then new budget account IDs (or any)
 * other type of ID generated by that session should start at 4000000
 */
const SAFE_ID_SUFFIX = 1e6;

module.exports = {
    SAFE_ID_SUFFIX,
};
