---
# Common tasks required to use PostgreSQL as either a client or a server
#
- name: Install PostgreSQL repository key
  apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Configure official PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present

- name: Install required packages
  apt:
    name: ['postgresql-server-dev-{{database_postgresql_version}}', 'postgresql-client-{{database_postgresql_version}}', 'python3-psycopg2']
    state: present
